interface iCountry { name:string};

export const CountryList : iCountry[] = [
 {name:"Germany"},
 {name:"Afghanistan"},
 {name:"Albania"},
 {name:"Algeria"},
 {name:"Andorra"},
 {name:"Angola"},
 {name:"Antigua and Barbuda"},
 {name:"Argentina"},
 {name:"Armenia"},
 {name:"Aruba"},
 {name:"Australia"},
 {name:"Austria"},
 {name:"Azerbaijan"},
 {name:"Bahamas"},
 {name:"Bahrain"},
 {name:"Bangladesh"},
 {name:"Barbados"},
 {name:"Belarus"},
 {name:"Belgium"},
 {name:"Belize"},
 {name:"Benin"},
 {name:"Bermuda"},
 {name:"Bhutan"},
 {name:"Bolivia"},
 {name:"Bosnia and Herzegovina"},
 {name:"Botswana"},
 {name:"Brazil"},
 {name:"Brunei"},
 {name:"Bulgaria"},
 {name:"Burkina Faso"},
 {name:"Burundi"},
 {name:"Cambodia"},
 {name:"Cameroon"},
 {name:"Canada"},
 {name:"Cape Verde"},
 {name:"Central African Republic"},
 {name:"Chad"},
 {name:"Chile"},
 {name:"Peoples Republic of China"},
 {name:"Republic of China (Taiwan)"},
 {name:"Colombia"},
 {name:"Comoros"},
 {name:"Democratic Republic of the Congo"},
 {name:"Republic of the Congo"},
 {name:"Costa Rica"},
 {name:"Cote dIvoire"},
 {name:"Croatia"},
 {name:"Cuba"},
 {name:"Republic of Cyprus"},
 {name:"Czech Republic"},
 {name:"Denmark"},
 {name:"Djibouti"},
 {name:"Dominica"},
 {name:"Dominican Republic"},
 {name:"East Timor"},
 {name:"Ecuador"},
 {name:"Egypt"},
 {name:"El Salvador"},
 {name:"Equatorial Guinea"},
 {name:"Eritrea"},
 {name:"Estonia"},
 {name:"Ethiopia"},
 {name:"Fiji"},
 {name:"Finland"},
 {name:"France"},
 {name:"Faroe Islands"},
 {name:"Gabon"},
 {name:"Gambia"},
 {name:"Georgia"},
 {name:"Germany"},
 {name:"Ghana"},
 {name:"Greece"},
 {name:"Grenada"},
 {name:"Guatemala"},
 {name:"Guinea"},
 {name:"Guinea-Bissau"},
 {name:"Guyana"},
 {name:"Haiti"},
 {name:"Honduras"},
 {name:"Hungary"},
 {name:"Iceland"},
 {name:"India"},
 {name:"Indonesia"},
 {name:"Iran"},
 {name:"Iraq"},
 {name:"Ireland"},
 {name:"Israel"},
 {name:"Italy"},
 {name:"Jamaica"},
 {name:"Japan"},
 {name:"Jordan"},
 {name:"Kazakhstan"},
 {name:"Kenya"},
 {name:"Kiribati"},
 {name:"Korea"},
 {name:"Korea, North"},
 {name:"Korea, South"},
 {name:"Kuwait"},
 {name:"Kyrgyzstan"},
 {name:"Laos"},
 {name:"Latvia"},
 {name:"Lebanon"},
 {name:"Lesotho"},
 {name:"Liberia"},
 {name:"Libya"},
 {name:"Liechtenstein"},
 {name:"Lithuania"},
 {name:"Luxembourg"},
 {name:"Republic of Macedonia"},
 {name:"Madagascar"},
 {name:"Malawi"},
 {name:"Malaysia"},
 {name:"Maldives"},
 {name:"Mali"},
 {name:"Malta"},
 {name:"Marshall Islands"},
 {name:"Mauretania"},
 {name:"Mauritius"},
 {name:"Mexico"},
 {name:"Federated States of Micronesia"},
 {name:"Moldova"},
 {name:"Monaco"},
 {name:"Mongolia"},
 {name:"Montenegro"},
 {name:"Morocco"},
 {name:"Mozambique"},
 {name:"Myanmar"},
 {name:"Namibia"},
 {name:"Nauru"},
 {name:"Nepal"},
 {name:"Netherlands"},
 {name:"New Zealand"},
 {name:"Nicaragua"},
 {name:"Niger"},
 {name:"Nigeria"},
 {name:"Niue"},
 {name:"North Korea"},
 {name:"Norway"},
 {name:"Oman"},
 {name:"Pakistan"},
 {name:"Palau"},
 {name:"Panama"},
 {name:"Papua New Guinea"},
 {name:"Paraguay"},
 {name:"Peru"},
 {name:"Philippines"},
 {name:"Poland"},
 {name:"Portugal"},
 {name:"Puerto Rico"},
 {name:"Qatar"},
 {name:"Romania"},
 {name:"Russia"},
 {name:"Rwanda"},
 {name:"Saint Kitts and Nevis"},
 {name:"Saint Lucia"},
 {name:"Saint Vincent and the Grenadines"},
 {name:"Samoa"},
 {name:"San Marino"},
 {name:"Sao Tome and Principe"},
 {name:"Saudi Arabia"},
 {name:"Serbia"},
 {name:"Seychelles"},
 {name:"Sierra Leone"},
 {name:"Singapore"},
 {name:"Slovakia"},
 {name:"Slovenia"},
 {name:"Solomon Islands"},
 {name:"Somalia"},
 {name:"South Africa"},
 {name:"South Korea"},
 {name:"South Sudan"},
 {name:"Spain"},
 {name:"Sri Lanka"},
 {name:"Sudan"},
 {name:"Suriname"},
 {name:"Swaziland"},
 {name:"Sweden"},
 {name:"Switzerland"},
 {name:"Syria"},
 {name:"Taiwan"},
 {name:"Tajikistan"},
 {name:"Tanzania"},
 {name:"Tatarstan"},
 {name:"Thailand"},
 {name:"Tibet"},
 {name:"Togo"},
 {name:"Tonga"},
 {name:"Trinidad and Tobago"},
 {name:"Tunisia"},
 {name:"Turkey"},
 {name:"Turkmenistan"},
 {name:"Tuvalu"},
 {name:"Uganda"},
 {name:"Ukraine"},
 {name:"United Arab Emirates"},
 {name:"United Kingdom"},
 {name:"United States"},
 {name:"Uruguay"},
 {name:"Uzbekistan"},
 {name:"Vanuatu"},
 {name:"Vatican City"},
 {name:"Venezuela"},
 {name:"Vietnam"},
 {name:"Yemen"},
 {name:"Zambia"},
 {name:"Zimbabwe"}
];

export const CountryList_de : iCountry[] =
  [
  {name:"Deutschland"},
 {name:"Ägypten"},
 {name:"Äthiopien"},
 {name:"Afghanistan"},
 {name:"Albanien"},
 {name:"Algerien"},
 {name:"Andorra"},
 {name:"Angola"},
 {name:"Argentinien"},
 {name:"Armenien"},
 {name:"Aserbaidschan"},
 {name:"Australien"},
 {name:"Bangladesh"},
 {name:"Belgien"},
 {name:"Benin"},
 {name:"Bolivien"},
 {name:"Bosnien-Herzegowina"},
 {name:"Botswana"},
 {name:"Brasilien"},
 {name:"Bulgarien"},
 {name:"Burkina Faso"},
 {name:"Burundi"},
 {name:"Chile"},
 {name:"China"},
 {name:"Costa Rica"},
 {name:"Dänemark"},
 {name:"Deutschland"},
 {name:"Dominikanische Republik"},
 {name:"Ecuador"},
 {name:"Elfenbeinküste"},
 {name:"El Salvador"},
 {name:"Eritrea"},
 {name:"Estland"},
 {name:"Finnland"},
 {name:"Frankreich"},
 {name:"Gabun"},
 {name:"Gambia"},
 {name:"Georgien"},
 {name:"Ghana"},
 {name:"Griechenland"},
 {name:"Großbritannien"},
 {name:"Guatemala"},
 {name:"Haiti"},
 {name:"Honduras"},
 {name:"Indien"},
 {name:"Indonesien"},
 {name:"Irak"},
 {name:"Iran"},
 {name:"Irland"},
 {name:"Island"},
 {name:"Israel"},
 {name:"Italien"},
 {name:"Jamaika"},
 {name:"Japan"},
 {name:"Jordanien"},
 {name:"Kambodscha"},
 {name:"Kamerun"},
 {name:"Kanada"},
 {name:"Kasachstan"},
 {name:"Kenia"},
 {name:"Kirgisistan"},
 {name:"Kolumbien"},
 {name:"Kongo"},
 {name:"Kosovo"},
 {name:"Kroatien"},
 {name:"Kuba"},
 {name:"Kuwait"},
 {name:"Laos"},
 {name:"Lettland"},
 {name:"Libanon"},
 {name:"Liberia"},
 {name:"Libyen"},
 {name:"Liechtenstein"},
 {name:"Litauen"},
 {name:"Luxemburg"},
 {name:"Madagaskar"},
 {name:"Malawi"},
 {name:"Malaysia"},
 {name:"Mali"},
 {name:"Malta"},
 {name:"Marokko"},
 {name:"Mauretanien"},
 {name:"Mazedonien"},
 {name:"Mexiko"},
 {name:"Mocambique"},
 {name:"Moldawien"},
 {name:"Mongolei"},
 {name:"Montenegro"},
 {name:"Myanmar"},
 {name:"Namibia"},
 {name:"Nepal"},
 {name:"Neuseeland"},
 {name:"Nicaragua"},
 {name:"Niederlande"},
 {name:"Niger"},
 {name:"Nigeria"},
 {name:"Nordkorea"},
 {name:"Norwegen"},
 {name:"Österreich"},
 {name:"Pakistan"},
 {name:"Palästina"},
 {name:"Panama"},
 {name:"Paraquay"},
 {name:"Peru"},
 {name:"Philippinen"},
 {name:"Polen"},
 {name:"Portugal"},
 {name:"Ruanda"},
 {name:"Rumänien"},
 {name:"Russland"},
 {name:"Sambia"},
 {name:"Saudi-Arabien"},
 {name:"Schweden"},
 {name:"Schweiz"},
 {name:"Senegal"},
 {name:"Serbien"},
 {name:"Sierra Leone"},
 {name:"Simbabwe"},
 {name:"Slowakei"},
 {name:"Slowenien"},
 {name:"Somalia"},
 {name:"Spanien"},
 {name:"Sri Lanka"},
 {name:"Sudan"},
 {name:"Südafrika"},
 {name:"Südkorea"},
 {name:"Syrien"},
 {name:"Tadschikistan"},
 {name:"Taiwan"},
 {name:"Tansania"},
 {name:"Thailand"},
 {name:"Togo"},
 {name:"Tschad"},
 {name:"Tschechien"},
 {name:"Türkei"},
 {name:"Tunesien"},
 {name:"Turkmenistan"},
 {name:"Uganda"},
 {name:"Ukraine"},
 {name:"Ungarn"},
 {name:"Uruquay"},
 {name:"USA"},
 {name:"Usbekistan"},
 {name:"Venezuela"},
 {name:"Vietnam"},
 {name:"Weißrussland"},
 {name:"Zentralafrikanischeu Republik"},
 {name:"Zypern"}
];


//interface countryPlus { name:string ; code:string};
/*
export const CountryList : countryPlus[] = [
  {name:'Afghanistan', code: 'AF'},
  {name:'Åland Islands', code: 'AX'},
  {name:'Albania', code: 'AL'},
  {name:'Algeria', code: 'DZ'},
  {name:'American Samoa', code: 'AS'},
  {name:'AndorrA', code: 'AD'},
  {name:'Angola', code: 'AO'},
  {name:'Anguilla', code: 'AI'},
  {name:'Antarctica', code: 'AQ'},
  {name:'Antigua and Barbuda', code: 'AG'},
  {name:'Argentina', code: 'AR'},
  {name:'Armenia', code: 'AM'},
  {name:'Aruba', code: 'AW'},
  {name:'Australia', code: 'AU'},
  {name:'Austria', code: 'AT'},
  {name:'Azerbaijan', code: 'AZ'},
  {name:'Bahamas', code: 'BS'},
  {name:'Bahrain', code: 'BH'},
  {name:'Bangladesh', code: 'BD'},
  {name:'Barbados', code: 'BB'},
  {name:'Belarus', code: 'BY'},
  {name:'Belgium', code: 'BE'},
  {name:'Belize', code: 'BZ'},
  {name:'Benin', code: 'BJ'},
  {name:'Bermuda', code: 'BM'},
  {name:'Bhutan', code: 'BT'},
  {name:'Bolivia', code: 'BO'},
  {name:'Bosnia and Herzegovina', code: 'BA'},
  {name:'Botswana', code: 'BW'},
  {name:'Bouvet Island', code: 'BV'},
  {name:'Brazil', code: 'BR'},
  {name:'British Indian Ocean Territory', code: 'IO'},
  {name:'Brunei Darussalam', code: 'BN'},
  {name:'Bulgaria', code: 'BG'},
  {name:'Burkina Faso', code: 'BF'},
  {name:'Burundi', code: 'BI'},
  {name:'Cambodia', code: 'KH'},
  {name:'Cameroon', code: 'CM'},
  {name:'Canada', code: 'CA'},
  {name:'Cape Verde', code: 'CV'},
  {name:'Cayman Islands', code: 'KY'},
  {name:'Central African Republic', code: 'CF'},
  {name:'Chad', code: 'TD'},
  {name:'Chile', code: 'CL'},
  {name:'China', code: 'CN'},
  {name:'Christmas Island', code: 'CX'},
  {name:'Cocos (Keeling) Islands', code: 'CC'},
  {name:'Colombia', code: 'CO'},
  {name:'Comoros', code: 'KM'},
  {name:'Congo', code: 'CG'},
  {name:'Congo, The Democratic Republic of the', code: 'CD'},
  {name:'Cook Islands', code: 'CK'},
  {name:'Costa Rica', code: 'CR'},
  {name:'Cote D\'Ivoire', code: 'CI'},
  {name:'Croatia', code: 'HR'},
  {name:'Cuba', code: 'CU'},
  {name:'Cyprus', code: 'CY'},
  {name:'Czech Republic', code: 'CZ'},
  {name:'Denmark', code: 'DK'},
  {name:'Djibouti', code: 'DJ'},
  {name:'Dominica', code: 'DM'},
  {name:'Dominican Republic', code: 'DO'},
  {name:'Ecuador', code: 'EC'},
  {name:'Egypt', code: 'EG'},
  {name:'El Salvador', code: 'SV'},
  {name:'Equatorial Guinea', code: 'GQ'},
  {name:'Eritrea', code: 'ER'},
  {name:'Estonia', code: 'EE'},
  {name:'Ethiopia', code: 'ET'},
  {name:'Falkland Islands (Malvinas)', code: 'FK'},
  {name:'Faroe Islands', code: 'FO'},
  {name:'Fiji', code: 'FJ'},
  {name:'Finland', code: 'FI'},
  {name:'France', code: 'FR'},
  {name:'French Guiana', code: 'GF'},
  {name:'French Polynesia', code: 'PF'},
  {name:'French Southern Territories', code: 'TF'},
  {name:'Gabon', code: 'GA'},
  {name:'Gambia', code: 'GM'},
  {name:'Georgia', code: 'GE'},
  {name:'Germany', code: 'DE'},
  {name:'Ghana', code: 'GH'},
  {name:'Gibraltar', code: 'GI'},
  {name:'Greece', code: 'GR'},
  {name:'Greenland', code: 'GL'},
  {name:'Grenada', code: 'GD'},
  {name:'Guadeloupe', code: 'GP'},
  {name:'Guam', code: 'GU'},
  {name:'Guatemala', code: 'GT'},
  {name:'Guernsey', code: 'GG'},
  {name:'Guinea', code: 'GN'},
  {name:'Guinea-Bissau', code: 'GW'},
  {name:'Guyana', code: 'GY'},
  {name:'Haiti', code: 'HT'},
  {name:'Heard Island and Mcdonald Islands', code: 'HM'},
  {name:'Holy See (Vatican City State)', code: 'VA'},
  {name:'Honduras', code: 'HN'},
  {name:'Hong Kong', code: 'HK'},
  {name:'Hungary', code: 'HU'},
  {name:'Iceland', code: 'IS'},
  {name:'India', code: 'IN'},
  {name:'Indonesia', code: 'ID'},
  {name:'Iran, Islamic Republic Of', code: 'IR'},
  {name:'Iraq', code: 'IQ'},
  {name:'Ireland', code: 'IE'},
  {name:'Isle of Man', code: 'IM'},
  {name:'Israel', code: 'IL'},
  {name:'Italy', code: 'IT'},
  {name:'Jamaica', code: 'JM'},
  {name:'Japan', code: 'JP'},
  {name:'Jersey', code: 'JE'},
  {name:'Jordan', code: 'JO'},
  {name:'Kazakhstan', code: 'KZ'},
  {name:'Kenya', code: 'KE'},
  {name:'Kiribati', code: 'KI'},
  {name:'Korea, Democratic People\'S Republic of', code: 'KP'},
  {name:'Korea, Republic of', code: 'KR'},
  {name:'Kuwait', code: 'KW'},
  {name:'Kyrgyzstan', code: 'KG'},
  {name:'Lao People\'S Democratic Republic', code: 'LA'},
  {name:'Latvia', code: 'LV'},
  {name:'Lebanon', code: 'LB'},
  {name:'Lesotho', code: 'LS'},
  {name:'Liberia', code: 'LR'},
  {name:'Libyan Arab Jamahiriya', code: 'LY'},
  {name:'Liechtenstein', code: 'LI'},
  {name:'Lithuania', code: 'LT'},
  {name:'Luxembourg', code: 'LU'},
  {name:'Macao', code: 'MO'},
  {name:'Macedonia, The Former Yugoslav Republic of', code: 'MK'},
  {name:'Madagascar', code: 'MG'},
  {name:'Malawi', code: 'MW'},
  {name:'Malaysia', code: 'MY'},
  {name:'Maldives', code: 'MV'},
  {name:'Mali', code: 'ML'},
  {name:'Malta', code: 'MT'},
  {name:'Marshall Islands', code: 'MH'},
  {name:'Martinique', code: 'MQ'},
  {name:'Mauritania', code: 'MR'},
  {name:'Mauritius', code: 'MU'},
  {name:'Mayotte', code: 'YT'},
  {name:'Mexico', code: 'MX'},
  {name:'Micronesia, Federated States of', code: 'FM'},
  {name:'Moldova, Republic of', code: 'MD'},
  {name:'Monaco', code: 'MC'},
  {name:'Mongolia', code: 'MN'},
  {name:'Montserrat', code: 'MS'},
  {name:'Morocco', code: 'MA'},
  {name:'Mozambique', code: 'MZ'},
  {name:'Myanmar', code: 'MM'},
  {name:'Namibia', code: 'NA'},
  {name:'Nauru', code: 'NR'},
  {name:'Nepal', code: 'NP'},
  {name:'Netherlands', code: 'NL'},
  {name:'Netherlands Antilles', code: 'AN'},
  {name:'New Caledonia', code: 'NC'},
  {name:'New Zealand', code: 'NZ'},
  {name:'Nicaragua', code: 'NI'},
  {name:'Niger', code: 'NE'},
  {name:'Nigeria', code: 'NG'},
  {name:'Niue', code: 'NU'},
  {name:'Norfolk Island', code: 'NF'},
  {name:'Northern Mariana Islands', code: 'MP'},
  {name:'Norway', code: 'NO'},
  {name:'Oman', code: 'OM'},
  {name:'Pakistan', code: 'PK'},
  {name:'Palau', code: 'PW'},
  {name:'Palestinian Territory, Occupied', code: 'PS'},
  {name:'Panama', code: 'PA'},
  {name:'Papua New Guinea', code: 'PG'},
  {name:'Paraguay', code: 'PY'},
  {name:'Peru', code: 'PE'},
  {name:'Philippines', code: 'PH'},
  {name:'Pitcairn', code: 'PN'},
  {name:'Poland', code: 'PL'},
  {name:'Portugal', code: 'PT'},
  {name:'Puerto Rico', code: 'PR'},
  {name:'Qatar', code: 'QA'},
  {name:'Reunion', code: 'RE'},
  {name:'Romania', code: 'RO'},
  {name:'Russian Federation', code: 'RU'},
  {name:'RWANDA', code: 'RW'},
  {name:'Saint Helena', code: 'SH'},
  {name:'Saint Kitts and Nevis', code: 'KN'},
  {name:'Saint Lucia', code: 'LC'},
  {name:'Saint Pierre and Miquelon', code: 'PM'},
  {name:'Saint Vincent and the Grenadines', code: 'VC'},
  {name:'Samoa', code: 'WS'},
  {name:'San Marino', code: 'SM'},
  {name:'Sao Tome and Principe', code: 'ST'},
  {name:'Saudi Arabia', code: 'SA'},
  {name:'Senegal', code: 'SN'},
  {name:'Serbia and Montenegro', code: 'CS'},
  {name:'Seychelles', code: 'SC'},
  {name:'Sierra Leone', code: 'SL'},
  {name:'Singapore', code: 'SG'},
  {name:'Slovakia', code: 'SK'},
  {name:'Slovenia', code: 'SI'},
  {name:'Solomon Islands', code: 'SB'},
  {name:'Somalia', code: 'SO'},
  {name:'South Africa', code: 'ZA'},
  {name:'South Georgia and the South Sandwich Islands', code: 'GS'},
  {name:'Spain', code: 'ES'},
  {name:'Sri Lanka', code: 'LK'},
  {name:'Sudan', code: 'SD'},
  {name:'Suriname', code: 'SR'},
  {name:'Svalbard and Jan Mayen', code: 'SJ'},
  {name:'Swaziland', code: 'SZ'},
  {name:'Sweden', code: 'SE'},
  {name:'Switzerland', code: 'CH'},
  {name:'Syrian Arab Republic', code: 'SY'},
  {name:'Taiwan, Province of China', code: 'TW'},
  {name:'Tajikistan', code: 'TJ'},
  {name:'Tanzania, United Republic of', code: 'TZ'},
  {name:'Thailand', code: 'TH'},
  {name:'Timor-Leste', code: 'TL'},
  {name:'Togo', code: 'TG'},
  {name:'Tokelau', code: 'TK'},
  {name:'Tonga', code: 'TO'},
  {name:'Trinidad and Tobago', code: 'TT'},
  {name:'Tunisia', code: 'TN'},
  {name:'Turkey', code: 'TR'},
  {name:'Turkmenistan', code: 'TM'},
  {name:'Turks and Caicos Islands', code: 'TC'},
  {name:'Tuvalu', code: 'TV'},
  {name:'Uganda', code: 'UG'},
  {name:'Ukraine', code: 'UA'},
  {name:'United Arab Emirates', code: 'AE'},
  {name:'United Kingdom', code: 'GB'},
  {name:'United States', code: 'US'},
  {name:'United States Minor Outlying Islands', code: 'UM'},
  {name:'Uruguay', code: 'UY'},
  {name:'Uzbekistan', code: 'UZ'},
  {name:'Vanuatu', code: 'VU'},
  {name:'Venezuela', code: 'VE'},
  {name:'Viet Nam', code: 'VN'},
  {name:'Virgin Islands, British', code: 'VG'},
  {name:'Virgin Islands, U.S.', code: 'VI'},
  {name:'Wallis and Futuna', code: 'WF'},
  {name:'Western Sahara', code: 'EH'},
  {name:'Yemen', code: 'YE'},
  {name:'Zambia', code: 'ZM'},
  {name:'Zimbabwe', code: 'ZW'}
]
    */
